/**
 * @fileoverview A list of global / international observance days.
 * @see https://gabriellelods.medium.com/a-list-of-global-international-observances-for-2021-821c0f5c8ae
 */

module.exports = [
  ['01/01', 'New Year'],
  ['04/01', 'World Braille Day'],
  ['06/01', 'World War Orphans Day'],
  ['07/01', 'International Programmers’ Day'],
  ['14/01', 'World Logic Day'],
  ['15/01', 'Wikipedia Day'],
  ['17/01', 'World Religion Day'],
  ['19/01', 'Popcorn Day'],
  ['21/01', 'International Hugging Day'],
  ['24/01', 'International Day of Education'],
  ['24/01', 'World Leprosy Day'],
  ['26/01', 'International Customs Day'],
  ['27/01', 'Family Literacy Day'],
  ['28/01', 'Data Privacy Day'],
  ['31/01', 'International Zebra Day'],
  ['31/01', 'World Leprosy Eradication Day'],
  ['01/02', 'World Aspergillosis Day'],
  ['01/02', 'World Hijab Day'],
  ['02/02', 'Groundhog Day'],
  ['02/02', 'World Wetlands Day'],
  ['04/02', 'World Cancer Day'],
  ['05/02', 'World Nutella Day'],
  ['06/02', 'Ice Cream for Breakfast Day'],
  ['06/02', 'No Phone Day'],
  ['06/02', 'International Day of Zero Tolerance to Female Genital Mutilation'],
  ['07/02', 'International Safer Internet Day'],
  ['10/02', 'World Pulses Day'],
  ['11/02', 'International Day of Women and Girls in Science'],
  ['11/02', 'World Day of the Sick'],
  ['12/02', 'Darwin Day'],
  ['13/02', 'World Radio Day'],
  ['14/02', 'Saint Valentine’s Day'],
  ['14/02', 'World Bonobo Day'],
  ['15/02', 'International Childhood Cancer Day'],
  ['15/02', 'Singles Awareness Day'],
  ['15/02', 'World Hippopotamus Day'],
  ['17/02', 'Random Acts of Kindness Day'],
  ['20/02', 'World Day of Social Justice'],
  ['20/02', 'World Pangolin Day'],
  ['21/02', 'International Mother Language Day'],
  ['22/02', 'World Scout Day'],
  ['22/02', 'World Thinking Day'],
  ['27/02', 'International Polar Bear Day'],
  ['27/02', 'World Sustainable Energy Day'],
  ['28/02', 'World Day without Facebook'],
  ['01/03', 'Self-Injury Awareness Day'],
  ['01/03', 'World Civil Defence Day'],
  ['01/03', 'Zero Discrimination Day'],
  ['01/03', 'World Compliment Day'],
  ['01/03', 'World Tennis Day'],
  ['02/03', 'Employee Appreciation Day'],
  ['03/03', 'World Wildlife Day'],
  ['04/03', 'World Engineering Day for Sustainable Development'],
  ['08/03', 'International Women’s Day'],
  ['10/03', 'Middle Name Pride Day'],
  ['10/03', 'No Smoking Day'],
  ['11/03', 'World Kidney Day'],
  ['12/03', 'Solar Appreciation Day'],
  ['12/03', 'World Glaucoma Day'],
  ['14/03', 'International Day of Action for Rivers'],
  ['14/03', 'International Day of Mathematics'],
  ['14/03', 'Pi Day'],
  ['14/03', 'Steak and Blowjob Day'],
  ['15/03', 'Buzzards Day'],
  ['15/03', 'World Consumer Rights Day'],
  ['15/03', 'World Contact Day'],
  ['18/03', 'Global Recycling Day'],
  ['19/03', 'Taxonomist Appreciation Day'],
  ['19/03', 'World Sleep Day'],
  ['20/03', 'International Day of Happiness'],
  ['20/03', 'World Frog Day'],
  ['20/03', 'World Oral Health Day'],
  ['20/03', 'World Rights to Water Day'],
  ['20/03', 'World Sparrow Day'],
  ['21/03', 'Anal Cancer Awareness Day'],
  ['21/03', 'International Day for the Elimination of Racial Discrimination'],
  ['21/03', 'International Day of Forests'],
  ['21/03', 'International Day of Nowruz'],
  ['21/03', 'World Down Syndrome Day'],
  ['21/03', 'World Planting Day'],
  ['21/03', 'World Poetry Day'],
  ['21/03', 'World Wood Day'],
  ['22/03', 'International Seal Day'],
  ['22/03', 'World Water Day'],
  ['23/03', 'World Bear Day'],
  ['23/03', 'World Meteorological Day'],
  ['24/03', 'World Tuberculosis Day'],
  [
    '25/03',
    'International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade',
  ],
  ['25/03', 'Tolkien Reading Day'],
  ['26/03', 'Purple Day for Epilepsy'],
  ['27/03', 'Earth Hour'],
  ['27/03', 'World Theatre Day'],
  ['30/03', 'World Bipolar Day'],
  ['31/03', 'Manatee Appreciation Day'],
  ['01/04', 'April Fool’s Day'],
  ['02/04', 'International Children’s Book Day'],
  ['02/04', 'Male Escorts’ Day'],
  ['02/04', 'World Autism Awareness Day'],
  ['03/04', 'World Aquatic Animal Day'],
  ['04/04', 'International Day for Mine Awareness'],
  ['04/04', 'International Pillow Fight Day'],
  ['06/04', 'International Day of Sport for Development and Peace'],
  ['07/04', 'International Beaver Day'],
  ['07/04', 'World Health Day'],
  ['08/04', 'Zoo Lovers Day'],
  ['10/04', 'Arbor Day'],
  ['10/04', 'Siblings Day'],
  ['10/04', 'World Homeopathy Day'],
  ['11/04', 'Safe Motherhood Day'],
  ['12/04', 'Equal Pay Day'],
  ['15/04', 'World Art Day'],
  ['15/04', 'World Bleeding Disorders Awareness Day'],
  ['16/04', 'World Voice Day'],
  ['17/04', 'Bat Appreciation Day'],
  ['17/04', 'World Hemophilia Day'],
  ['18/04', 'International Day for Monuments and Sites'],
  ['20/04', '420: International day for cannabis-related protests and events'],
  ['21/04', 'Day of Silence'],
  ['21/04', 'World Fish Migration Day'],
  ['22/04', 'World Earth Day'],
  ['23/04', 'World Book and Copyright Day'],
  ['24/04', 'Fashion Revolution Day'],
  ['24/04', 'International Sculpture Day'],
  ['24/04', 'World Day for Laboratory Animals'],
  ['24/04', 'World Meningitis Day'],
  ['25/04', 'DNA day'],
  ['25/04', 'World Malaria Day'],
  ['26/04', 'World Intellectual Property Day'],
  ['27/04', 'International Hyena Day'],
  ['27/04', 'World Tapir Day'],
  ['28/04', 'World Day for Safety and Health at Work'],
  ['29/04', 'Day of Remembrance for all Victims of Chemical Warfare'],
  ['29/04', 'International Dance Day'],
  ['30/04', 'International Jazz Day'],
  ['01/05', 'International Labour Day'],
  ['01/05', 'World Naked Gardening Day'],
  ['02/05', 'World Laughter Day'],
  ['02/05', 'World Tuna Day'],
  ['03/05', 'International Leopard Day'],
  ['03/05', 'Wild Koala Day'],
  ['03/05', 'World Press Freedom Day'],
  ['04/05', 'Coal Miners Day'],
  ['04/05', 'International Firefighters’ Day'],
  ['04/05', 'Star Wars Day'],
  ['04/05', 'World Asthma Day'],
  ['05/05', 'International Midwives Day'],
  ['05/05', 'World Portuguese Language Day'],
  ['06/05', 'International No Diet Day'],
  ['07/05', 'International Masturbation Day'],
  ['07/05', 'No Pants Day'],
  ['07/05', 'World Athletics Day'],
  ['07/05', 'World Password Day'],
  ['07/05', 'World Wide Day of Genital Autonomy'],
  ['08/05', 'World Donkey Day'],
  ['08/05', 'World Fair Trade Day'],
  ['08/05', 'World Ovarian Cancer Day'],
  ['08/05', 'World Red Cross Day'],
  ['09/05', 'Mother’s Day'],
  ['12/05', 'International Nurses Day'],
  ['13/05', 'World Cocktail Day'],
  ['14/05', 'Endangered Species Day'],
  ['15/05', 'Armed Forces Day'],
  ['15/05', 'International Day of Families'],
  ['16/05', 'International Day of Light'],
  ['16/05', 'International Day of Living Together in Peace'],
  ['17/05', 'International Day Against Homophobia, Transphobia and Biphobia'],
  ['17/05', 'World Telecommunication and Information Society Day'],
  ['18/05', 'International Museum Day'],
  ['18/05', 'World AIDS Vaccine Day'],
  ['19/05', 'World Inflammatory Bowel Disease (IBD) Day'],
  ['20/05', 'Global Accessibility Awareness Day'],
  ['20/05', 'World Autoimmune / Autoinflammatory Arthritis Day'],
  ['20/05', 'World Bee Day'],
  ['21/05', 'Bike-to-Work Day'],
  ['21/05', 'World Day for Cultural Diversity for Dialogue and Development'],
  ['22/05', 'International Day for Biological Diversity'],
  ['23/05', 'World Turtle Day'],
  ['25/05', 'Geek Pride Day'],
  ['25/05', 'International Missing Children’s Day'],
  ['25/05', 'Towel Day'],
  ['25/05', 'World Multiple Sclerosis Day'],
  ['26/05', 'World Redhead Day'],
  ['27/05', 'World Otter Day'],
  ['28/05', 'Menstrual Hygiene Day'],
  ['29/05', 'International Day of UN Peacekeepers'],
  ['31/05', 'World No-Tobacco Day'],
  ['31/05', 'World Parrot Day'],
  ['01/06', 'Global Day of Parents'],
  ['01/06', 'World Milk Day'],
  ['01/06', 'World Reef Day'],
  ['02/06', 'International Sex Workers Day'],
  ['03/06', 'World Bicycle Day'],
  ['04/06', 'International Day of Innocent Children Victims of Aggression'],
  ['05/06', 'World Environment Day'],
  ['07/06', 'World Food Safety Day'],
  ['08/06', 'World Brain Tumour Day'],
  ['08/06', 'World Oceans Day'],
  ['09/06', 'Coral Triangle Day'],
  ['11/06', 'International Lynx Day'],
  ['12/06', 'World Day Against Child Labour'],
  ['12/06', 'Global Wellness Day'],
  ['12/06', 'World Wide Knit in Public Day'],
  ['13/06', 'International Albinism Awareness Day'],
  ['14/06', 'World Blood Donor Day'],
  ['15/06', 'World Wind Day'],
  ['16/06', 'World Sea Turtle Day'],
  ['17/06', 'World Croc Day'],
  ['17/06', 'World Day to Combat Desertification and Drought'],
  ['18/06', 'Autistic Pride Day'],
  ['19/06', 'World Sickle Cell Awareness Day'],
  ['20/06', 'World Father’s Day'],
  ['20/06', 'World Refugee Day'],
  ['21/06', 'Go Skateboarding Day'],
  ['21/06', 'International Day of Yoga'],
  ['21/06', 'International Surfing Day'],
  ['21/06', 'World Giraffe Day'],
  ['21/06', 'World Humanist Day'],
  ['21/06', 'World Music Day'],
  ['22/06', 'World Camel Day'],
  ['22/06', 'World Rainforest Day'],
  ['23/06', 'International Olympic Day'],
  ['23/06', 'International Widow’s Day'],
  ['24/06', 'Take Your Dog to Work Day'],
  ['25/06', 'World Vitiligo Day'],
  ['26/06', 'International Day against Drug Abuse and Illicit Trafficking'],
  ['26/06', 'International Day in Support of Victims of Torture'],
  ['26/06', 'World Refrigeration Day'],
  ['27/06', 'International PTSD Awareness Day'],
  ['28/06', 'CAPS LOCK DAY'],
  ['30/06', 'International Asteroid Day'],
  ['01/07', 'Doctor’s Day'],
  ['02/07', 'World UFO Day'],
  ['03/07', 'International Day of Cooperatives'],
  ['03/07', 'International Free Hugs Day'],
  ['06/07', 'International Kissing Day'],
  ['06/07', 'World Zoonoses Day'],
  ['07/07', 'World Chocolate Day'],
  ['11/07', 'World Population Day'],
  ['12/07', 'Malala Day'],
  ['12/07', 'Simplicity Day'],
  ['14/07', 'International Non-Binary People’s Day'],
  ['14/07', 'Shark Awareness Day'],
  ['14/07', 'World Chimpanzee Day'],
  ['14/07', 'World Orca Day'],
  ['15/07', 'World Youth Skills Day'],
  ['17/07', 'World Day for International Justice'],
  ['17/07', 'World Emoji Day'],
  ['18/07', 'Nelson Mandela International Day'],
  ['20/07', 'International Chess Day'],
  ['22/07', 'Pi Approximation Day'],
  ['26/07', 'Esperanto Day'],
  ['26/07', 'International Day for the Conservation of the Mangrove Ecosystem'],
  ['28/07', 'World Hepatitis Day'],
  ['28/07', 'World Nature Conservation Day'],
  ['29/07', 'International Tiger Day'],
  ['30/07', 'International Day of Friendship'],
  ['30/07', 'System Administrator Appreciation Day'],
  ['04/08', 'International Clouded Leopard Day'],
  ['06/08', 'International Beer Day'],
  ['08/08', 'International Cat Day'],
  ['09/08', 'International Day of the World’s Indigenous People'],
  ['10/08', 'World Lion Day'],
  ['12/08', 'International Youth Day'],
  ['12/08', 'World Elephant Day'],
  ['13/08', 'Friday the 13th'],
  ['13/08', 'International Lefthanders Day'],
  ['13/08', 'International Wolf Day'],
  ['19/08', 'World Humanitarian Day'],
  ['19/08', 'World Orangutan Day'],
  ['19/08', 'World Photography Day'],
  ['20/08', 'World Mosquito Day'],
  ['21/08', 'World Senior Citizens Day'],
  [
    '23/08',
    'International Day for the Remembrance of the Slave Trade and its Abolition',
  ],
  ['26/08', 'Women’s Equality Day'],
  ['26/08', 'World Dog Day'],
  ['29/08', 'International Day against Nuclear Tests'],
  ['30/08', 'International Day of the Disappeared'],
  ['30/08', 'International Whale Shark Day'],
  ['31/08', 'International Overdose Awareness Day'],
  ['04/09', 'International Vulture Awareness Day'],
  ['04/09', 'World Sexual Health Day'],
  ['05/09', 'International Day of Charity'],
  ['06/09', 'Fight Procrastination Day'],
  ['08/09', 'International Literacy Day'],
  ['08/09', 'World Physical Therapy Day'],
  ['10/09', 'World Suicide Prevention Day'],
  ['13/09', 'International Programmers’ Day'],
  ['15/09', 'International Day of Democracy'],
  ['16/09', 'International Day of Preservation'],
  ['17/09', 'Still’s Disease Awareness Day'],
  ['17/09', 'World Patient Safety Day'],
  ['18/09', 'International Red Panda Day'],
  ['18/09', 'World Cleanup Day'],
  ['18/09', 'World Water Monitoring Day'],
  ['19/09', 'International Talk Like a Pirate Day'],
  ['20/09', 'International Day of University Sport'],
  ['21/09', 'International Day of Peace'],
  ['21/09', 'Zero Emissions Day'],
  ['22/09', 'Hobbit Day'],
  ['22/09', 'Rose Day (Welfare of Cancer patients)'],
  ['22/09', 'World Car Free Day'],
  ['22/09', 'World Rhino Day'],
  ['23/09', 'International Celebrate Bisexuality Day'],
  ['23/09', 'International Day of Sign Languages'],
  ['24/09', 'World Gorilla Day'],
  ['25/09', 'As You Wish Day'],
  ['26/09', 'World Cassowary Day'],
  ['26/09', 'World Contraception Day'],
  ['26/09', 'World Environmental Health Day'],
  ['26/09', 'World Maritime Day'],
  ['26/09', 'World Rivers Day'],
  ['27/09', 'World Tourism Day'],
  ['28/09', 'Ask a Stupid Question Day'],
  ['28/09', 'International Day for the Universal Access to Information'],
  ['28/09', 'International Safe Abortion Day'],
  ['28/09', 'World Rabies Day'],
  ['29/09', 'World Heart Day'],
  ['30/09', 'International Translation Day'],
  ['01/10', 'International Coffee Day'],
  ['01/10', 'World Smile Day'],
  ['01/10', 'International Day of Older Persons'],
  ['01/10', 'World Vegetarian Day'],
  ['02/10', 'International Day of Non-Violence'],
  ['02/10', 'World Farm Animals Day'],
  ['04/10', 'World Animal Day'],
  ['04/10', 'World Habitat Day'],
  ['05/10', 'World Teachers’ Day'],
  ['06/10', 'Energy Efficiency Day'],
  ['06/10', 'World Cerebral Palsy Day'],
  ['09/10', 'World Post Day'],
  ['10/10', 'World Mental Health Day'],
  ['11/10', 'International Day of the Girl Child'],
  ['13/10', 'International Day for Disaster Reduction'],
  ['14/10', 'International E-Waste Day'],
  ['14/10', 'World Sight Day'],
  ['14/10', 'World Standards Day'],
  ['15/10', 'Global Handwashing Day'],
  ['15/10', 'Pregnancy and Infant Loss Remembrance Day'],
  ['15/10', 'World Students Day'],
  ['15/10', 'World White Cane Day (guiding the blind)'],
  ['16/10', 'World Food Day'],
  ['17/10', 'International Day for the Eradication of Poverty'],
  ['18/10', 'World Okapi Day'],
  ['18/10', 'World Vasectomy Day'],
  ['20/10', 'International Sloth Day'],
  ['20/10', 'World Osteoporosis Day'],
  ['20/10', 'World Statistics Day'],
  ['21/10', 'Reptile Awareness Day'],
  ['22/10', 'International Stuttering Awareness Day'],
  ['22/10', 'International Wombat Day'],
  ['23/10', 'International Snow Leopard Day'],
  ['23/10', 'Mole Day'],
  ['24/10', 'Freshwater Dolphin Day'],
  ['24/10', 'International Day of Climate Action'],
  ['24/10', 'International Gibbon Day'],
  ['24/10', 'United Nations Day'],
  ['24/10', 'World Development Information Day'],
  ['26/10', 'Intersex Awareness Day'],
  ['27/10', 'Sustainability Day!'],
  ['27/10', 'World Day for Audiovisual Heritage'],
  ['29/10', 'World Lemur Day'],
  ['29/10', 'World Stroke Day'],
  ['30/10', 'World Thrift Day'],
  ['31/10', 'Halloween'],
  ['01/11', 'World Vegan Day'],
  ['02/11', 'All Souls’ Day'],
  ['02/11', 'International Day to End Impunity for Crimes against Journalists'],
  [
    '04/11',
    'International Day Against Violence and Bullying at School, including Cyberbullying',
  ],
  ['05/11', 'World Tsunami Day'],
  [
    '06/11',
    'International Day for Preventing the Exploitation of the Environment in War and Armed Conflict',
  ],
  ['07/11', 'Infant Protection Day'],
  ['08/11', 'Intersex Day of Remembrance'],
  ['09/11', 'World Freedom Day'],
  ['10/11', 'Transport Day'],
  ['10/11', 'World Science Day for Peace and Development'],
  ['11/11', 'Armistice Day'],
  ['11/11', 'Singles’ Day'],
  ['12/11', 'World Pneumonia Day'],
  ['13/11', 'World Kindness Day'],
  [
    '14/11',
    'International Day against Illicit Trafficking in Cultural Property',
  ],
  ['14/11', 'World Diabetes Day'],
  ['16/11', 'International Day for Tolerance'],
  ['17/11', 'World Prematurity Day'],
  ['18/11', 'World Philosophy Day'],
  ['19/11', 'International Men’s Day'],
  ['19/11', 'World Toilet Day'],
  ['20/11', 'Transgender Day of Remembrance'],
  ['20/11', 'Universal Children’s Day'],
  ['21/11', 'World Day of Remembrance for Road Traffic Victims'],
  ['21/11', 'World Fisheries Day'],
  ['21/11', 'World Hello Day'],
  ['21/11', 'World Television Day'],
  ['25/11', 'International Day for the Elimination of Violence against Women'],
  ['26/11', 'Anti Obesity Day'],
  ['26/11', 'World Olive Tree Day'],
  ['27/11', 'Buy Nothing Day'],
  ['29/11', 'International Jaguar Day'],
  ['30/11', 'Cities for Life Day'],
  ['01/12', 'World AIDS Day'],
  ['02/12', 'International Day for the Abolition of Slavery'],
  ['03/12', 'International Day of Persons with Disabilities'],
  ['04/12', 'International Cheetah Day'],
  ['05/12', 'International Volunteer Day'],
  ['05/12', 'World Soil Day'],
  ['07/12', 'International Civil Aviation Day'],
  ['09/12', 'International Anti-Corruption Day'],
  ['10/12', 'Human Rights Day'],
  ['11/12', 'International Mountain Day'],
  ['11/12', 'UNICEF Day'],
  ['12/12', 'Universal Health Coverage Day'],
  ['14/12', 'Monkey Day'],
  ['14/12', 'World Energy Conservation Day'],
  ['15/12', 'International Tea Day'],
  ['17/12', 'International Day to End Violence Against Sex Workers'],
  ['18/12', 'International Migrants Day'],
  ['20/12', 'International Human Solidarity Day'],
  ['21/12', 'Global Orgasm'],
  ['25/12', 'Christmas Day'],
  ['26/12', 'Boxing Day'],
  ['31/12', 'New Year’s Eve'],
];
