{
    "slack": {
        "slackbot_webhook": ""
    },
    "postgres": {
        "connection_string": "postgres://postgres:postgres@127.0.0.1:5432/slackbot",
        "connection_string_reset": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
        "host": null,
        "pool_min": 2,
        "pool_max": 10,
        "migrations": {
            "directory": "./migrations/"
        },
    },
}
