{
    "postgres": {
        "connection_string": "postgres://postgres:postgres@127.0.0.1:5432/skgbot-dev",
        "connection_string_reset": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
        "host": null,
        "pool_min": 2,
        "pool_max": 10,
        "migrations": {
            "directory": "./migrations/migrations/"
        },
        "seed_directory": "./migrations/seeds"
    },
    "webserver": {
        "port": 8000,
        "backend_base_url": "http://localhost:8000",
        "enforce_ssl": false,
        "cookie_secure": false,
        "cors": {
            "allowed_origins": []
        }
    },
    "email": {
      "smtp_host": "gx2s-kc87.accessdomain.com",
      "smtp_port": 465,
      "smtp_secure": true,
      "auth_user": "hello@skgtech.io",
      "auth_password": "DO NOT SET - USE ENV VAR: SKGBOT_EMAIL_AUTH_PASSWORD"
    },
    "onboarding": {
      "mail_from": "\"SKGTech Bot 🤖\" <hello@skgtech.io>",
      "verification_expires_days": 7,
    },
    "discord": {
        "token": "DO NOT SET - USE ENV VAR: DISCORD_BOT_TOKEN",
        "commando": {
          "owner_uid": "DO NOT SET - USE ENV VAR: DISCORD_COMMANDO_UID"
        },
    }
}
