{
    "postgres": {
        "connection_string": "postgres://postgres:postgres@127.0.0.1:5432/skgbot-dev",
        "connection_string_reset": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
        "host": null,
        "pool_min": 2,
        "pool_max": 10,
        "migrations": {
            "directory": "./migrations/migrations/"
        },
        "seed_directory": "./migrations/seeds"
    },
    "webserver": {
        "port": 8000,
        "backend_base_url": "http://localhost:8000",
        "enforce_ssl": false,
        "cookie_secure": false,
        "cors": {
            "allowed_origins": []
        }
    },
    "discord": {
        "token": "DO NOT FILL - USE ENV VAR: DISCORD_BOT_TOKEN",
        "commando": {
          "owner_uid": "DO NOT FILL - USE ENV VAR: DISCORD_COMMANDO_UID"
        },
    }
}
